### ISSUE TITLE
Alarm Control Panel State arm_vaction is not supported

### ISSUE THREAD

**Issue by LuckyTriple7** [CyberDNS/Lupusec2Mqtt#29]
Hello,
is it possible to support the new **arm_vacation** state for this great Add On ?
I think the Lupus State home3 is available.

**Comment by CyberDNS** [comment]
I have integrated the functionality in the new version.
It is mapped to home3.
For the moment I published under Edge stream, it is version 2.0.0.

Best regard,
David
