### ISSUE TITLE
Burglary alarm

### ISSUE THREAD

**Issue by rkupfer2020** [CyberDNS/Lupusec2Mqtt#3]
Hi David,

Is it possible to receive the status in case of a "burglary alarm" in Home Assistant? 
I would like to "activate" some additional lights in Home Assistant in case of a burglary alarm. As far as I know the Lupusec (Zigbee) light switches can't be connected in both systems at the same time (Lupusec and Home Assistant). 
The idea behind is to release the connected Lupusec light switches (Zigbee) from XT2plus and connect them on Home Assistant (Zigbee). I mean not the Lupusec door, window, smoke or movement  sensors. 
With this idea it would be possible to manage the lights in a normal way in Home Assistant and in case of a alarm you can switch for example all lights in the house to "on".

Again, thank you very much for the quick fix concering the SSL certificate!

Best regards
Roger

**Comment by CyberDNS** [comment]
Hi Roger,

I pushed a new version (latest) to docker hub that adds a binary_sensor per area that shows if a burglar alarm is ongoing. 
Additionally I changed the poll time from 5sec to 2sec to make it more reactive.

Feel free to give me your feedback.

Best regards,
David

**Comment by rkupfer2020** [comment]
Hi David,

perfect idea! Thank you.
What are the status values to build the automation?
binary_sensor.area_1_alarm_status / binary_sensor.area_2_alarm_status = On / Off?

Best regards
Roger

**Comment by CyberDNS** [comment]
Hi Roger,

The status is Off = Safe and On = Unsafe. So this means that it will go from Off to On when a Burglar Alarm is active. It stays on for some time in the Lupusec central and this is reflected in this status. 

Best regards, 
David

**Comment by rkupfer2020** [comment]
Hi David,
what else can I say... Perfect. 
Thanky you very much!
Best regards
Roger
