### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by LuckyTriple7** [CyberDNS/Lupusec2Mqtt#30]
After Update to V2, Add On does not work.
Following Error in Log:

standard_init_linux.go:228: exec user process caused: exec format error

**Comment by CyberDNS** [comment]
Ok it seems to be related to Net 6 upgrade. Is it on a Raspi Pi that you are using the addon?

**Comment by LuckyTriple7** [comment]
yes, RPi 4

**Comment by CyberDNS** [comment]
I provided a new upgrade (v2.0.1) that should correct the problem.
I did not select the correct docker images for .NET 6 for the different platforms.

Best regards,
David

**Comment by LuckyTriple7** [comment]
I updated to V2.01. Looks good now, Thx.
