### ISSUE TITLE
How to setup Lupusec2Mqtt using docker(-compose)

### ISSUE THREAD

**Issue by s0n1c-hedgehog** [CyberDNS/Lupusec2Mqtt#31]
I am using Home Assistant as docker container and want to integrate my XT2 Plus but am struggeling with the configuration of Lupusec2Mqtt. 

Can you explain, how to setup the MQTT server and XT2 when I use Lupusec2Mqtt as a docker container? 

I built the Lupusec2Mqtt container using the Dockerfile of the repository. 

Thank you very much in advance!

**Comment by CyberDNS** [comment]
Hi,

I think the easiest will be to set the environment variable ASPNETCORE_HOMEASSISTANT__CONFIG to the path of the config. Probably you will need to use docker volumes if you want to access the config outside of your container.

The config file is described here: https://github.com/CyberDNS/Lupusec2Mqtt/blob/6b72554437a86882c63669488b31951a5e3162f0/CONTRIBUTING.md

Hope this helps.

Best regards,
David
