### ISSUE TITLE
Thermostates

### ISSUE THREAD

**Issue by christophgasser** [CyberDNS/Lupusec2Mqtt#33]
Hi,

is it possibel to add thermostates? I am a developer myself but never worked with Pyton, etc. and don't want to screw up the repository.

What I know is, that you can read the current temp. value from thermostates the same way as from any other temp. sensor. And you can set the target temp. using this api call: /action/deviceeditthermopost?id={id}&act=t_setpoint&thermo_setpoint={value} whereby you have to multiply the value by 1.000 (18° = 1800).

Thermostat sensors have TypeId 79 as far as I know.

I am more than happy to assist or to the dev work with a "little help from a friend".

**Comment by CyberDNS** [comment]
Hi,

Yes I think it should be possible to add thermostats.
The code is written in C#, you can fork the repository and then commit to the dev branch. It is not really possible te mess something up.
It would be good if you could already try to get the information from the thermostats and try to set for example the temperature. This would help a lot in integrating the functionality as I don't have personally thermostats connected to the Lupusec.
I can help in integrating the calls into the code base in the end.

Best regards,
David

**Comment by CyberDNS** [comment]
Issue is stale, will be closed.

**Comment by mbay0r** [comment]
hi, as i have Thermostats, are you still interessted in adding them? i could try give you the informations.

thanks

**Comment by CyberDNS** [comment]
Hi,
Yes no problem. 
So if you can provide me the necessary information, I will add them too.

Best regards,
David

**Comment by mbay0r** [comment]
i think, i have no time right now. should we leave it open that long, or close it first?

**Comment by CyberDNS** [comment]
Hi, no problem, we can leave it open.

**Comment by trashar** [comment]
Hi David,
thank you for this great HA addon. 

i hope the information will help you, to add the thermostate.

the type id is 79.
`{
            "area": 1,
            "zone": 11,
            "type": 79,
            "type_f": "{D_TYPE_79}",
            "name": "Heizung Zimmer Lotta",
            "tag": "",
            "cond": "",
            "cond_ok": "1",
            "battery": "",
            "battery_ok": "1",
            "tamper": "",
            "tamper_ok": "1",
            "bypass": 0,
            "rssi": "{WEB_MSG_STRONG}	9",
            "resp_mode": [
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "ammeter": "0",
            "ver": "TRV_00.00.03.09TC",
            "bypass_tamper": 0,
            "sid": "ZS:83b401",
            "su": 1,
            "alarm_status": "",
            "status_ex": "0",
            "hue": "-1",
            "sat": "-1",
            "ctemp": "-1",
            "hue_cmode": "-1",
            "hue_cie_x": "-1",
            "hue_cie_y": "-1",
            "hue_color_cap": "0",
            "nuki": "-1",
            "shutter_turn": 0,
            "status": "{WEB_MSG_TS_DEGREE}	19.18 {WEB_MSG_TRV_MANUAL} {WEB_MSG_TRV_VALVE}	10 {WEB_MSG_TRV_SETPOINT}	18.5"
        },`

in status you can see some information. 
{WEB_MSG_TS_DEGREE} is the current temp
{WEB_MSG_TRV_MANUAL} says, the manual mode is active
{WEB_MSG_TRV_VALVE} i don't really know
{WEB_MSG_TRV_SETPOINT} is the wanted temp

but with an extra api call for this thermostate you can get this (/deviceEditThermoGet?id=ZS:83b401)

`{
    "forms": {
        "thermoform": {
            "id": "ZS:83b401",
            "thermo_mode": "4",
            "thermo_setpoint": "1850",
            "thermo_c_setpoint": "-1",
            "thermo_fan_mode": "-1",
            "thermo_offset": "0",
            "thermo_remote": "0",
            "thermo_schd_setting": "0",
            "schd_week_mode": "-100",
            "prog": "1"
        }
    }
}`

thermo_mode can be 0 (off) or 4 (on)
thermo_setpoint is the wanted temp

the other values i dont know, but i dont test all options yet.

for edit the settings there should be the api endpoint at "deviceEditThermoPost". i will look close to it in the next few days.

i hope this could help to integrate the thermostates.
if i could help with more infos, ask me

Gruß
Björn

**Comment by trashar** [comment]
Good Morning,

i added the thermostates:

![image](https://github.com/user-attachments/assets/7baa6250-56eb-4c6d-9121-344a15cc84e4)
you could change the temperature, set to off or automate (if you configured a shedule plan in the lupusec).

i checked in the develop version in my branch at https://github.com/trashar/Lupusec2Mqtt/tree/feature/thermostate 

i test it some days and then i will create a pull request.

some questions to @CyberDNS 
is the code quality okay?
create the pull request after the water sensors are in the final release or it doesnt matter?! (i hope you understand what i mean)

best regards
Björn

**Comment by CyberDNS** [comment]
Hi Björn,

Nice work, well done, I checked the code in the fork, for me it is fine. 👍 

No problem to create the pull request before the water sensor is in the stable version. I normally let new features for several weeks or month in the edge version before pushing them into the stable version.

If you don't mind, you can also adapt the readme.md to add the thermostats to the "documentation" before publishing the pull request.

Anyway, thanks a lot for your contribution and making the addon even more useful for the community.

Br, 
David

**Comment by trashar** [comment]
Pull Request: https://github.com/CyberDNS/Lupusec2Mqtt/pull/89 

best regards Björn
