### ISSUE TITLE
Request for testing: New version >v3.0.0

### ISSUE THREAD

**Issue by CyberDNS** [CyberDNS/Lupusec2Mqtt#46]
Hi all,
@ChrisKeck, @maionaise, @scaiandre, @mentor7785, @mbay0r, @christophgasser, @Airbrando,  @LuckyTriple7, @bauerpower69, @rkupfer2020, @chheiss, @s0n1c-hedgehog 

I was currently working on a new model to make the integration of new devices easier. Another big change is that the MQTT library that was used has changed to [MQTTnet](https://github.com/dotnet/MQTTnet).
Can I ask you to test the new version on the edge lane?

**Here are some details what has changed:**
With the design of the new model you can register 3 different types of "objects":

StaticValue: This is used to provide static information in the home assistant configuration json that is pushed to MQTT
Query: This is used to query a state value on Lupusec and to be pushed as state to MQTT (HA)
Command: This is used to declare a command that is registered on a MQTT topic and that calls something on lupusec (ex. set an the alarm mode, or switch button on power switch)
The devices are now generated by a factory class per device, so that the old conversion class is gone and now every device can handle it's creation on it's own.

Also the poll loop has changed because it is now completely generic, so no special code anymore for alarm panels and switches etc. The class is located in the root folder of the project (MainLoop.cs)

Thank you very much and a "guter Rutsch" into the new year 🍾🍀
David

**Comment by mbay0r** [comment]
Works good for me.

**Comment by mentor7785** [comment]
I will test it after Christmas.
Thanks for that.

Frohe Weihnachten 🎄

**Comment by mentor7785** [comment]
Maybe I'm a little bit rusty - I installed and configure the edge-version and deactivate the regular version; restart HA.
After that, the "old" entities works, but there are no new entities for e.g. the shutters.

what's wrong?

**Comment by CyberDNS** [comment]
> Maybe I'm a little bit rusty - I installed and configure the edge-version and deactivate the regular version; restart HA.
> After that, the "old" entities works, but there are no new entities for e.g. the shutters.
> 
> what's wrong?

For the moment it is pure refactoring, I will integrate shutters in the next days.
I wanted just to ensure that all currently integrated devices are still working. (As I don't own all of them)

**Comment by mentor7785** [comment]
Ahhh okay - thanks.
The Christmas dinner pays its tribute ;)

**Comment by maionaise** [comment]
Nice, thanks! Couldn't find any problems yet, Nuki works too.

Auch von mir einen guten Rutsch!

**Comment by LuckyTriple7** [comment]
3.0.5 is working without Issues:

XT2
Motion Sensors
Door / Window Senesors

**Comment by tofrie** [comment]
Wie kann ich die Version installieren?

**Comment by mbay0r** [comment]
In HA die Edge-Version installieren. Vorher die andere entfernen.

**Comment by CyberDNS** [comment]
Hi all,

I have released v3.1.0 now on Edge and Stable.
The version corresponds to the last published Edge version (no new changes).

Thanks a lot for your support on testing this major version.

Best regards,
David
