### ISSUE TITLE
how to setup on Home Assistant image?

### ISSUE THREAD

**Issue by bauerpower69** [CyberDNS/Lupusec2Mqtt#5]
@CyberDNS

Dear David,

sorry for the question. I install the Home Assistant image and not the Docker version.
As I have seen that the docker environment is used for add-ons.
Is there a way to install Lupusec2Mqtt manually on my machine (RASPI 4b/8)?
Mosquitto broker is already install (via Add-ons) :-)

Would be great if you can give me a short info.

**1000 Thanks :-)** 

Joerg

**Comment by CyberDNS** [comment]
Hi Joerg,

I will try to make it available as an Home Assistant Add-on. In that way it can be directly downloaded and installed in the Home Assistant UI.
It's something that I never did, so I have to familiarize myself on how to implement an Add-on first.
I will come back to you when I have news.

Best regards,
David

**Comment by bauerpower69** [comment]
Dear David,

wow, you are my hero … :-) Please let me know if you need 
help in testing … translating … adaptation …

Warm regards and stay healthy!

Joerg

**Comment by CyberDNS** [comment]
Hi Joerg,

I have a first version working of all this. I tested it on an Intel based system. As I have no Raspberry up and running with HASS, you can do a first test. If there are problems that we cannot resolve by inspecting the logs, I will install a Raspberry with HASS.

I created a custom repository that you can add on your Homeassistant installation: https://github.com/CyberDNS/hassio-addons-repository

Then you will find the Lupusec2Mqtt addon with a sample configuration.
After starting, you should see the polling happening in the Logs tab of the add-on.

Best regards,
David

**Comment by CyberDNS** [comment]
After some problems on Arm based system, it is now working as an addon. Will close this issue.
