### ISSUE TITLE
Lupusec endities in HA not available after restart of HA Core.

### ISSUE THREAD

**Issue by rubinho76** [CyberDNS/Lupusec2Mqtt#60]
I noticed that the values of the Lupusec endities are not available after reloading HA.
I always have to restart the addon twice before values are displayed in the Lupusec endities.
It does not matter whether it is the Lupusec2Mqtt or Lupusec2Mqtt Edge addon. 
The log also looks normal so far, and via MQTT Explorer I see that the values always arrive in the MQTT broker.
Only the values of the endities are not available.

I am currently using the latest version of Lupusec2Mqtt Edge and HA 2023.5.3

However, the problem already exists with HA version HA 2023.4.0, maybe earlier.

Can anyone confirm this?

**Comment by JaniSchlumpf** [comment]
Can confirm the behaviour. Always need to Restart the AddOn after a HA reboot in order to get the states from unavailbale to show values. Using HA 2023.6.3, but was also the case for 2023.6.2.

**Comment by CyberDNS** [comment]
Hi I published a new version 3.1.3 on stable and edge that resolves this problem.

Have a nice day,
David
