### ISSUE TITLE
Smoke Detector

### ISSUE THREAD

**Issue by rkupfer2020** [CyberDNS/Lupusec2Mqtt#62]
Hi David, 
I would like to know if the state of the Lupusec Smoke detectors are published in Home Assistant. Something like on / off.
The idea behind this question is to send notifications if something happens when I am abroad and can't hear the alarm sound.

Best regards,
Roger

**Comment by CyberDNS** [comment]
Hi Roger,
For the moment the state is not yet published, because I didn't want to create smoke to see what is published on the API 😉.
I will leave the issue open, and if I find the time I will try to provoke a smoke alarm to inspect what is happening on the API in that case.
Best regards,
David

**Comment by TiDO2k** [comment]
@CyberDNS 
Status = alarm_status_ex = 0 (false) or 1 (true)

**Comment by CyberDNS** [comment]
See: https://github.com/CyberDNS/Lupusec2Mqtt/issues/69#issuecomment-2004968337

**Comment by CyberDNS** [comment]
@TiDO2k : Are the some detectors also working like expected?

**Comment by TiDO2k** [comment]
@CyberDNS Can't test it at the moment :)

**Comment by CyberDNS** [comment]
@TiDO2k ok no problem, I will leave the issue open then for the moment.

When this one is working, I will push a new stable 3.3.0.
Thanks for your commitment.

Br,
David

**Comment by st0n3d-rs** [comment]
Hello,
the state is not working at my smoke detectors.

thanks for your work

**Comment by CyberDNS** [comment]
Hi @st0n3d-rs ,

I published a new Edge version 3.3.2 that adds "DOORBELL" status to the vibration sensors. But not sure if this fix is resolving the issue for the smoke sensors, too. I think if we want to make the smoke sensors work, we have to do a proper reverse engineering with developer tools.

But anyway, you can give it a try.

Br, 
David

**Comment by mbay0r** [comment]
Hi David,

the smoke detectors don't work for me either, no alarm is detected. 

However, the smoke detector is recognized:

[14:44:36 INF] Device configured: RF:a7b50040 - Living room


thank you

**Comment by CyberDNS** [comment]
Hi @mbay0r,

Do you have the possibility to check with Developer tools of your browser how the state can be detected?

Br,
David

**Comment by mbay0r** [comment]
> Hi @mbay0r,
> 
> Do you have the possibility to check with Developer tools of your browser how the state can be detected?
> 
> Br, David

Yes, as soon as I have time, I will test it.

Thank you!

**Comment by CyberDNS** [comment]
Hi @mbay0r ,

I will close the issue for now, at the moment you or someone else has the time to do some testing, we can reopen it.

Br,
David
