### ISSUE TITLE
Temperature below zero

### ISSUE THREAD

**Issue by mucki12** [CyberDNS/Lupusec2Mqtt#64]
Hi,
maybe its just me? The temperature sensor delivers all temps below zero as zero (no negative values).

Example Lupusec:
<img width="1277" alt="image" src="https://github.com/CyberDNS/Lupusec2Mqtt/assets/92673795/aa3ed28e-4641-4441-8b8a-4f6a1649b357">

Same in HA:
<img width="1097" alt="image" src="https://github.com/CyberDNS/Lupusec2Mqtt/assets/92673795/90841c00-99ef-4505-b359-f6bfb020bc46">

Any ideas to fix this?

**Comment by CyberDNS** [comment]
I published just now an new Edge version 3.1.4. Can you check if it work now properly please?
After your feedback I will then push a new "stable" version.

BR,
David

**Comment by mucki12** [comment]
Thanks! I would like to test this. Is it enough to deactivate Lupus3MQTT in Home Assistant and install the edge version? Or do problems then arise with the (existing) entities?

**Comment by CyberDNS** [comment]
Yes exactly, you can stop the normal add in, then add the edge version. You can copy the configuration from the stable one.

**Comment by mucki12** [comment]
Perfect! Thanks again!

![image](https://github.com/CyberDNS/Lupusec2Mqtt/assets/92673795/dccb93c2-2c56-449e-b46f-20645830d72d)

![image](https://github.com/CyberDNS/Lupusec2Mqtt/assets/92673795/d5d0bd21-babf-4d6d-aa5e-87c709fdd4fe)

**Comment by CyberDNS** [comment]
Good to hear that it works now. 
You have put it in your freezer to test it? 🥶😆

I published the stable version just now, so you can switch back to that one.

Have a nice WE,
David

**Comment by mucki12** [comment]
Hehe. Yes - first I doubt that the communication will work, but no problem even in the freezer :-)

Thanks and nice WE.
