### ISSUE TITLE
HA Version 2024.X and higher not working with Lupusec2Mqtt

### ISSUE THREAD

**Issue by christophgasser** [CyberDNS/Lupusec2Mqtt#66]
This issue has been mentioned in another issue already. But the only option offered was to downgrade to HA 2023.X . That is not an option for me unfortunatly.
Is there any chance, that this component will be working on 2024.X in near future? Is there anything I can help on?

**Comment by CyberDNS** [comment]
Hi @christophgasser ,

I reopened the other issue #63 because it contains the complete history about the problem, will close this one instead.

Br,
David
