### ISSUE TITLE
Can you add "vibrations / shock detectors"?

### ISSUE THREAD

**Issue by TiDO2k** [CyberDNS/Lupusec2Mqtt#69]
Hi,

can you add "vibration detectors" to the integration? If you need anything, please let me know.
Shock sensor (Type 93)

Art.-Nr.:12105
EAN:4260195433885
LUPUSEC - Erschütterungsmelder

Thanks,
best regards,
TiDO

**Comment by CyberDNS** [comment]
Hi @TiDO2k,

Because I don't own this type of sensor. I would need the API description information that you can get while inspecting the changes that you see in the developer tools (F12) in the network tab. 
I would need the endpoint where the status is published and the value that shows the status, furthermore it would be helpful to get some payloads with different values or the different states that the sensor can output.

You could also check the source code, there you could inspect how the smoke detector is implemented, I think your sensor is quite similar to that one.

Best regards,
David

**Comment by TiDO2k** [comment]
Hi  @CyberDNS,

thanks for your fast response.
Is it not possible to copy it from https://github.com/schmupu/ioBroker.lupusec ?

**Comment by CyberDNS** [comment]
Hi @TiDO2k,

Thanks, please can you provide me the endpoint you called e.g. /action/deviceListGet or /action/deviceGet and also the different status values the sensor can take. I would need also the name of the attribute that is containing the status value.

**Example for window contact:**
Endpoint: HTTP POST on /action/deviceListGet
Attribute: status
Values: if status == "{WEB_MSG_DC_OPEN}" then "ON" else "OFF"

Br,
David

**Comment by CyberDNS** [comment]
Hi @TiDO2k,

I published just now a new version that adds the vibration detector (and also the state for smoke detector).
The version is Lupusec2Mqtt Edge v3.2.0.

So you can try if everything works like expected.

Br, 
David

**Comment by TiDO2k** [comment]
Device is integrated and all vibrations detectors are implemented.
Thanks.
@CyberDNS 
Is it posible to change the poll time to 0.5 sec? Can I do it myself in the configuration file?

**Comment by CyberDNS** [comment]
Good to hear that it is working.
@TiDO2k : Can you add an issue for the poll frequency please. For the moment it is not configurable but it is something that I can implement.

**Comment by TiDO2k** [comment]
hi @CyberDNS 
it's not working as expected.
did you use 
status_ex: 0 (false) or 1 (true)
or
status": "DOORBELL"
?

**Comment by CyberDNS** [comment]
Hi, 
I used status_ex: 0 (false) and 1 (true).
I saw just now your edit, so I should not use status_ex but status: "DOORBELL" -> ON and "" -> OFF?

Br.
David

**Comment by TiDO2k** [comment]
Hi David,
maybe implement both:
status_ex 0 or 1
and
status "doorbell" -> ON or "" ->OFF

**Comment by CyberDNS** [comment]
Hi @TiDO2k,

I need your input to correctly integrate the vibration sensor, as I can't test it myself. Could you clarify how to interpret status_ex and status for the sensor to be "ON" or "OFF"?

Should status_ex = 1 always mean the sensor is "ON"?
Does "DOORBELL" in status mean "ON", even if status_ex = 0?
Are there any other important status values?

I status can only take the DOORBELL value here are the different possibilities to combine status_ex and status:

**Variant A (OR):**
| `status_ex` | `status`   | Sensor State |
|-------------|------------|--------------|
| 0           | ""         | OFF          |
| 1           | ""         | ON           |
| 0           | "DOORBELL" | ON          |
| 1           | "DOORBELL" | ON           |

**Variant B (XOR):**
| `status_ex` | `status`   | Sensor State |
|-------------|------------|--------------|
| 0           | ""         | OFF          |
| 1           | ""         | ON           |
| 0           | "DOORBELL" | ON          |
| 1           | "DOORBELL" | OFF           |

**Variant C (AND):**
| `status_ex` | `status`   | Sensor State |
|-------------|------------|--------------|
| 0           | ""         | OFF          |
| 1           | ""         | OFF           |
| 0           | "DOORBELL" | OFF          |
| 1           | "DOORBELL" | ON           |

Your guidance is crucial for accurate implementation. 

Br,
David

**Comment by TiDO2k** [comment]
@CyberDNS 
Variant 1

Br,
TiDO

**Comment by CyberDNS** [comment]
Hi @TiDO2k ,

I implemented the Variant A now and published a new Edge version 3.3.2.

Happy testing :)
Br,
David

**Comment by CyberDNS** [comment]
Hi @TiDO2k, 

I hope the devices are working for you, as I didn't hear anything from you about the result of the testing I will close the issue for now.

Br,
David
