### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by Airbrando** [CyberDNS/Lupusec2Mqtt#76]
![image](https://github.com/CyberDNS/Lupusec2Mqtt/assets/21360554/732715c7-6443-4e9e-9d7a-2fcf87920958)

Since the newest update from HA i get this error when i toogle the alarm system. Can anybody help here ? THX

**Comment by ahamro** [comment]
You'll have to enter (one of) the Lupusec PIN code(s) (user code) in the Settings of the device 'Lupusec alarm', in the field 'Default code'.
![Screenshot 2024-06-07 193554](https://github.com/CyberDNS/Lupusec2Mqtt/assets/71564034/4619860f-30ac-4f92-aff3-b00c21535d30)

**Comment by Airbrando** [comment]
I dont have this. I have lupusec2mqtt
Or where is this setting ? I can disable the alarm but not enable it. Pleas help. Before the update was everything has worked

**Comment by ahamro** [comment]
I'm using the embedded Lupusec integration and it had exactly the same error message.
